<?php

namespace App\Http\Controllers;

use App\Http\Resources\ReportResource;
use App\Http\Resources\ResponseHelper;
use App\Models\Consultation;
use App\Models\Doctor;
use App\Models\Report;
use Carbon\Carbon;
use Exception;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use OpenApi\Annotations as OA;

/**
 * @OA\Tag(
 *     name="Reports",
 *     description="API Endpoints for managing reports generated by doctors"
 * )
 */
class ReportController extends Controller
{
    /**
     * @OA\Get(
     *     path="/doctor/report",
     *     operationId="createDoctorReport",
     *     tags={"Reports"},
     *     summary="Create a new report for today",
     *     description="Creates a new daily report for the authenticated doctor",
     *     security={{"bearerAuth":{}}},
     *     @OA\Response(
     *         response=201,
     *         description="Report created successfully",
     *         @OA\JsonContent(
     *             @OA\Property(property="success", type="boolean", example=true),
     *             @OA\Property(property="message", type="string", example="success make report"),
     *             @OA\Property(property="data", type="object",
     *                 @OA\Property(property="report", type="object",
     *                     @OA\Property(property="id", type="integer", example=1),
     *                     @OA\Property(property="id_doctor", type="integer", example=1),
     *                     @OA\Property(property="patient_count", type="integer", example=5),
     *                     @OA\Property(property="income", type="number", example=250),
     *                     @OA\Property(property="report_date", type="string", format="date", example="2025-04-30")
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response=401,
     *         description="Unauthorized",
     *         @OA\JsonContent(
     *             @OA\Property(property="message", type="string", example="Unauthenticated")
     *         )
     *     ),
     *     @OA\Response(
     *         response=500,
     *         description="Report generation failed",
     *         @OA\JsonContent(
     *             @OA\Property(property="success", type="boolean", example=false),
     *             @OA\Property(property="message", type="string", example="failed to make consultation"),
     *             @OA\Property(property="error", type="string", example="Report for today already exists")
     *         )
     *     )
     * )
     */
    public function makeReport()
    {
        try {
            $doctorId = Auth::user()->id;

            $existingReport = Report::where('id_doctor', $doctorId)
                ->whereDate('report_date', Carbon::today())
                ->first();

            if ($existingReport) {
                throw new Exception("Report for today already exists");
            }

            $patientCount = Consultation::where('id_doctor', $doctorId)
                ->whereDate('consultation_date', Carbon::today())->count();
            $doctor = Doctor::findOrFail($doctorId);
            Log::info($doctor);
            $income = $patientCount * $doctor->consultation_fee;

            $report = Report::create([
                'id_doctor'    => $doctorId,
                'patient_count' => $patientCount,
                'income'       => $income,
                'report_date'  => Carbon::today(),
            ]);
            return ResponseHelper::success(["report" => new ReportResource($report)], "success make report", 201);
        } catch (Exception $e) {
            return ResponseHelper::error("failed to make consultation", 500, $e->getMessage());
        }
    }

    /**
     * @OA\Get(
     *     path="/doctor/reports",
     *     operationId="getAllDoctorReports",
     *     tags={"Reports"},
     *     summary="Get all doctor reports",
     *     description="Retrieves all reports generated by the authenticated doctor",
     *     security={{"bearerAuth":{}}},
     *     @OA\Response(
     *         response=200,
     *         description="Reports retrieved successfully",
     *         @OA\JsonContent(
     *             @OA\Property(property="success", type="boolean", example=true),
     *             @OA\Property(property="message", type="string", example="success retrieve the report"),
     *             @OA\Property(property="data", type="object",
     *                 @OA\Property(
     *                     property="reports",
     *                     type="array",
     *                     @OA\Items(
     *                         @OA\Property(property="id", type="integer", example=1),
     *                         @OA\Property(property="id_doctor", type="integer", example=1),
     *                         @OA\Property(property="patient_count", type="integer", example=5),
     *                         @OA\Property(property="income", type="number", example=250),
     *                         @OA\Property(property="report_date", type="string", format="date", example="2025-04-30")
     *                     )
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response=401,
     *         description="Unauthorized",
     *         @OA\JsonContent(
     *             @OA\Property(property="message", type="string", example="Unauthenticated")
     *         )
     *     ),
     *     @OA\Response(
     *         response=500,
     *         description="Failed to retrieve reports",
     *         @OA\JsonContent(
     *             @OA\Property(property="success", type="boolean", example=false),
     *             @OA\Property(property="message", type="string", example="failed to make consultation"),
     *             @OA\Property(property="error", type="string", example="Internal Server Error")
     *         )
     *     )
     * )
     */
    public function index()
    {
        try {
            $reports = Report::where('id_doctor', Auth::user()->id)->get();
            return ResponseHelper::success(['reports' => ReportResource::collection($reports)], "success retreive the report", 200);
        } catch (Exception $e) {
            return ResponseHelper::error("failed to make consultation", 500, $e->getMessage());
        }
    }
}
